### ISSUE TITLE
minimum levels

### ISSUE THREAD

**Issue by mcwave** [Guernouille/Stadium_Editor#1]
Pokemon in the Medium-Slow Experience Group have a minimum level of 2. Due to experience under-flows, uploading level 1 Pokemon in the Medium-Slow Experience Group are elevated to level 100.
Pokemon in the Fast, Medium-Fast, and Slow Experience Group have a minimum level of 1.

**Comment by Guernouille** [comment]
The minimum levels listed are not accounting for glitches and ACE. It's the minimum levels possible without glitches, be it by catching, in-game gifts, game corner, and in-game trades.

There's an option that lets the randomizer ignore these min levels (effectively giving every Pokémon a min level of 2)
