### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by LightningThunder1** [Guernouille/Stadium_Editor#4]
Sorry but I've been trying to compile this into an .exe. I've spent the last few days trying without success.

**Comment by GenericMadScientist** [comment]
What version of Qt are you trying? This was made before Qt 6, so try Qt 5.

**Comment by LightningThunder1** [comment]
I was using mingw-w64.
These are the instructions that I was following..
https://www.tutorialspoint.com/How-to-compile-and-run-the-Cplusplus-program

**Comment by GenericMadScientist** [comment]
Ah, yes that's not going to work. Install Qt Creator and the last version of Qt 5, then try following https://doc.qt.io/qtcreator/creator-build-example-application.html except with opening this project (although trying to build an example first is probably a good idea).

**Comment by LightningThunder1** [comment]
I downloaded it, and spent a few more hours on it. I was able to do a untitled project with the code predone and everything.
Do you have a exe of the latest source code (June 20, 2017?)

**Comment by GenericMadScientist** [comment]
I've compiled it for you: [Pokemon_Stadium_Editor.zip](https://github.com/Guernouille/Stadium_Editor/files/12754430/Pokemon_Stadium_Editor.zip).
